spring:
 datasource:
  url: jdbc:mysql://localhost:3306/cloud_vendor
  username: root
  password: 201270
 jpa.hibernate.ddl_auto: create
management:
 endpoints:
  web:
   exposure:
    include: '*'
   base-path: '/mangement-dashboard'
 endpoint:
  health:
   show-details: always
 
 